{{- if not .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voting-app.postgresSecretName" . }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "postgres.auth.password is required" .Values.postgres.auth.password | quote }}
  DB_USER: {{ .Values.postgres.auth.username | quote }}
  DB_PASS: {{ required "postgres.auth.password is required" .Values.postgres.auth.password | quote }}
{{- end }}
