apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: voting-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/madhu123-4/docker-samples-voting-app
    targetRevision: master
    path: Helm

  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true