name: Helm lint and Build images and deploy

on:
  push:
    paths:
      - "worker/**"
      - ".github/workflows/**"
      - "Helm/**"
    branches:
      - patch
jobs:
  helm-test:
    if: github.event_name == 'push'
    uses: madhu123-4/Happy-Helming/.github/workflows/helm-test.yaml@main
  

  build-images:
    if: github.event_name == 'merge'
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - service: vote
            context: ./vote
          - service: result
            context: ./result
          - service: worker
            context: ./worker
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{vars.ACR_URL}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and publish ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ vars.ACR_URL }}/${{ matrix.service }}:${{ github.ref_name }}

  deploy:
    if: github.event_name == 'push'
    needs: build-images
    uses: madhu123-4/Happy-Helming/.github/workflows/helm-deploy.yaml@main
    with:
      environment: Testing
      chart_directory: ./Helm
      release_name: voting-app
      namespace: default
      image_tag: ${{ github.ref_name }}
      timeout: 10
    secrets: inherit
