name: Helm PR validation

on:
  pull_request:
    paths:
      - "Helm/**"
      - "vote/**"
      - "result/**"
      - "worker/**"
      - ".github/workflows/**"
    types: [opened, synchronize, reopened]  

permissions:
  contents: read

jobs:
  helm-test:
    uses: madhu123-4/Happy-Helming/.github/workflows/helm-test.yaml@main
    with:
      chart_directory: ./Helm
      timeout: 10

  