name: versioning

on:
   pull_request:
     types: [opened, synchronize, reopened, edited]
     branches:
       - master
jobs:
   automatic-tagging:
      uses: madhu123-4/Happy-Helming/.github/workflows/automatic-tagging.yaml@master





