name: versioning

on:
   pull_request:
     types: [opened, synchronize, reopened, edited]
     branches:
       - main
jobs:
   automatic-tagging:
      uses: madhu123-4/Happy-Helming/.github/workflows/automatic-tagging.yaml@main





